### PR TITLE
[YUNIKORN-382]Update kubectl in dockerfile to comply with the support policy

### PR DESCRIPTION
**Pull request by HuangTing-Yao**
Update the kubectl in Dockerfile from 1.14.7 to 1.16.13.

### CODE REVIEW

**Comment by wilfred-s** [comment]
Please hold of committing until we have it clear that we drop 1.14 from support in the next release. Officially we cannot support 1.14 if we use kubectl 1.16.

**Comment by yangwwei** [comment]
Thanks for raising this up. Right, according to https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet. If we update kubelet to 1.16, that won't work with K8s 1.14/1.15. However, if we use kubelet 1.14, that is supposed to work with 1.14/1.15/1.16.
@HuangTing-Yao did you see any issue while using 1.14 kubelet working with K8s 1.16?

**Comment by HuangTing-Yao** [comment]
@yangwwei Here is talking about kubectl, not kubelet.
And I haven't try kubelet 1.14 in k8s 1.16, both my kubelet and kubectl is 1.16.
according to [kubectl](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl), if we use kubectl 1.16 that can only support to k8s 1.15.
Or should we modify kubectl in dockerfile to 1.15.x ?

**Comment by yangwwei** [comment]
> @yangwwei Here is talking about kubectl, not kubelet.
Oh yes, thanks for the correction.

> And I haven't try kubelet 1.14 in k8s 1.16, both my kubelet and kubectl in cluster is 1.16, the other kubectl in scheduler image is 1.14.7. It doesn't show any big issue.
> according to [kubectl](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl), if we use kubectl 1.16 that can only support to k8s 1.15.
> Or should we modify kubectl in dockerfile to 1.15.x ?

Yep. I think we should try 1.15. That looks to be safer.

**Review by wilfred-s — APPROVED** [review]
lgtm, committing the change

**Pull request closed without merging**
