### PR TITLE
[YUNIKORN-939] shim e2e tests fail on go 1.15

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
e2e tests are failing. Need to use Go version 1.16.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-939

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by kingamarton** [comment]
@pbacsko it seems that there are other needed change. Can you please check the failure and fix it as well?

**Comment by wilfred-s** [comment]
Looks like we need to update the go.mod & go.sum file to get a clean build to pass:
```
	go get github.com/apache/incubator-yunikorn-scheduler-interface/lib/go/si@v0.11.1-0.20210825113556-88f21e44dc01
	go get github.com/prometheus/client_golang/prometheus@v1.7.1
	go get github.com/googleapis/gnostic/openapiv2@v0.4.1
	go get google.golang.org/grpc/binarylog/grpc_binarylog_v1@v1.27.1
	go get github.com/prometheus/client_model/go@v0.2.0
	go get golang.org/x/crypto/ssh/terminal@v0.0.0-20201002170205-7f63de1d35b0
```

**Comment by pbacsko** [comment]
> Looks like we need to update the go.mod & go.sum file to get a clean build to pass:
> 
> ```
> 	go get github.com/apache/incubator-yunikorn-scheduler-interface/lib/go/si@v0.11.1-0.20210825113556-88f21e44dc01
> 	go get github.com/prometheus/client_golang/prometheus@v1.7.1
> 	go get github.com/googleapis/gnostic/openapiv2@v0.4.1
> 	go get google.golang.org/grpc/binarylog/grpc_binarylog_v1@v1.27.1
> 	go get github.com/prometheus/client_model/go@v0.2.0
> 	go get golang.org/x/crypto/ssh/terminal@v0.0.0-20201002170205-7f63de1d35b0
> ```

To me it's weird. We've already been dependent on `si@v0.11.1-0.20210825113556-88f21e44dc01` since August. I can perfectly compile k8shim locally.

**Comment by wilfred-s** [comment]
With the `go get` download changes I still see a failure when I run just the 2e2 tests in a clean system. As part of the test run a `go get` is run to install gingko and gomega. This modifies the `go.mod` file.  That modification could well be the cause and we should move away from `go get` to install the binaries we need and use `go install`. I have not seen any issues after a change to `go install`

**Review by kingamarton — APPROVED** [review]

**Pull request merged**
