### PR TITLE
[YUNIKORN-354] Update YK base docker images to UBI

### PR DESCRIPTION
**Pull request by adamantal**
Updated the base Docker image for the container

Questions:
- [ ] where should be changed the helm charts?
- [ ] should the base image for the admission controller be changed?
- [ ] add license for UBI image if needed

Tested:
locally using `make clean run` on  docker-desktop

### CODE REVIEW

**Comment by kingamarton** [comment]
@adamantal The helm charts are located in the release repository: https://github.com/apache/incubator-yunikorn-release/tree/master/helm-charts/yunikorn

**Comment by yangwwei** [comment]
Looks like the e2e test is failing due to:
> Step 1/34 : FROM registry.redhat.io/ubi8/go-toolset:1.12.8-45
Get https://registry.redhat.io/v2/ubi8/go-toolset/manifests/1.12.8-45: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication

**Comment by adamantal** [comment]
Since the RedHat Docker registry requires authentication which may conflict with the ASF policies we decided to abandon this patch and try a downstream solution.

**Comment by wilfred-s** [comment]
UBIs from RedHat are set to be moved into authenticated access only registries. That will require a RH account and thus acceptance of the terms that come with it. We would still need further entitlements to be able to add packages etc in the base image. 
I don't think that is a good idea for an Apache release.

I am a -1 on this change.

**Pull request closed without merging**
