### PR TITLE
[YUNIKORN-861] add affinity support to task-group for gang scheduling placeholders

### PR DESCRIPTION
**Pull request by brickyard**
### What is this PR for?
Gang-scheduling in Yunikorn requires the use of placeholder pods to guarantee placement of pods during the execution lifecycle.  These placeholder pods will eventually be replaced by the actual application pod and therefore must have the same nodeSelector, tolerations, and affinity as the application pods in order to perform replacement properly.  This PR adds affinity support to the `task-groups` configuration.  

Example applied with the`yunikorn.apache.org/task-groups` label - 

```json
[
    {
        "name": "d-spark-application-k07xl",
        "minMember": 1,
        "minResource": {
            "cpu": "1",
            "memory": "3200Mi"
        }
    },
    {
        "name": "e-spark-application-k07xl",
        "minMember": 5,
        "minResource": {
            "cpu": "6",
            "memory": "13000Mi"
        },
        "affinity": {
            "podAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [
                    {
                        "topologyKey": "topology.kubernetes.io/zone",
                        "labelSelector": {
                            "matchExpressions": [
                                {
                                    "key": "sparkoperator.k8s.io/app-name",
                                    "operator": "In",
                                    "values": [
                                        "spark-application-k07xl"
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
]

```

### What type of PR is it?
* [X] - Improvement

### What is the Jira issue?
* https://issues.apache.org/jira/browse/YUNIKORN-861

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [X] - It needs documentation.

### CODE REVIEW

**Comment by yangwwei** [comment]
hi @brickyard  thanks for working on this. overall it looks good. 
Since this PR modified `types.go`, I think we need to run the code-gen: https://github.com/apache/incubator-yunikorn-k8shim/blob/4c4d15b68e3285e58f92c65d187c3dd482167721/Makefile#L223-L233. Can you pls check this? @HuangTing-Yao, pls do cross-check, thanks!

**Comment by brickyard** [comment]
> . Can you pls check this? @HuangTing-Yao, pls do cross-check, thanks!

I ran `make code_gen` but it didnt generate any changed files.   Im not a golang dev, so I could have screwed this up ;-)

**Comment by yangwwei** [comment]
> > . Can you pls check this? @HuangTing-Yao, pls do cross-check, thanks!
> 
> I ran `make code_gen` but it didnt generate any file changes. Im not a golang dev, so I could have screwed this up ;-)

Understood. To run this, you will need to set up the dir structure as the required form, otherwise, the tool will not be able to recognize. Like mentioned here:
```
# If you want to re-run the code-generator to generate code, 
 # Please make sure the directory structure must be the example. 
 # ex: github.com/apache/incubator-yunikorn-k8shim 
 # Also you need to set you GOPATH environmental variables first. 
 # If GOPATH is empty, we will set it to "$HOME/go". 
```

pls give it a try, if you still have issues. I can take a look at that later today and see if I have a good setup to run this. Thanks

**Comment by yangwwei** [comment]
hi @brickyard 

you can run `make code_gen` with the following steps:

1. Clone the repo to the local workspace like: `/Users/wyang/workspace/github.com/apache/incubator-yunikorn-k8shim`
2. Set GOPATH to the workspace: `export GOPATH=/Users/wyang/workspace/`
3. Run `make code_gen`

this works for me and I get the changes like the patch attached (have to compress it to zip in order to attach it here). Please see if these steps work for you. Thanks.
[PR-306.patch.zip](https://github.com/apache/incubator-yunikorn-k8shim/files/7240060/PR-306.patch.zip)
.

**Review by HuangTing-Yao — APPROVED** [review]
LGTM, wait for test result.

**Pull request merged**
