### PR TITLE
[YUNIKORN-953] Investigate of kubeflow/training-operator

### PR DESCRIPTION
**Pull request by lowc1012**
### What is this PR for?
Add dockerfile and distributed MNIST example 

related to : https://github.com/apache/incubator-yunikorn-site/pull/96

### What type of PR is it?
* [ ] - Bug Fix
* [X] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-953)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by yangwwei** [comment]
@lowc1012 could you please add a README file in `deployment/examples/tfjob` folder? It will be easier for others to refer and run the same. Once you updated and let's see how the e2e test goes, we had a couple of issues recently which just got fixed. We are not expecting to see any failures with the changes here (non-code changes).

**Comment by lowc1012** [comment]
@yangwwei
Ok, Thanks for the reminder. I' m working on it.

**Comment by lowc1012** [comment]
The e2e test is still failing. I ran e2e test on my mac and found it is a flaky test.
I will look into this problem.

**Review by yangwwei — APPROVED** [review]
LGTM, thanks for adding the instructions!

**Pull request merged**
