### PR TITLE
[YUNIKORN-135] Move the scheduler-interface related constants from the markdown to the common package

### PR DESCRIPTION
**Pull request by adamantal**

### CODE REVIEW

**Comment by adamantal** [comment]
Thanks for the review @wilfred-s 

So to sum up, I will put the following constants to SI:
```go
// Cluster
const DefaultNodeAttributeHostNameKey = "si.io/hostname"
const DefaultNodeAttributeRackNameKey = "si.io/rackname"

// Application
const LabelApp = "app"
const LabelApplicationID = "applicationId"
const LabelQueueName = "queue"

// Resource
const Memory = "memory"
const CPU = "vcore"

// Spark
const SparkLabelAppID = "spark-app-selector"
const SparkLabelRole = "spark-role"
const SparkLabelRoleDriver = "driver"
```
and I will put the following constants into shim:
```go
// Cluster
const DefaultRackName = "/rack-default"

// Application
const ApplicationDefaultQueue = "root.sandbox"
const DefaultPartition = "default"

// Configuration
const DefaultConfigMapName = "yunikorn-configs"
```

**Comment by wilfred-s** [comment]
> So to sum up, I will put the following constants to SI:
> 
> ```go
> 
> // Application
> const LabelApp = "app"
> const LabelApplicationID = "applicationId"
> const LabelQueueName = "queue"
> 
> // Resource
> const Memory = "memory"
> const CPU = "vcore"
> 
> // Spark
> const SparkLabelAppID = "spark-app-selector"
> const SparkLabelRole = "spark-role"
> const SparkLabelRoleDriver = "driver"
> ```

These constants are only used by the shim. The Application ones are used to pull data out of k8 objects and then inserted into fixed locations in messages. The first spark one is just to pull data out of the spark app, the SparkLabelRole* is never even referenced and look obsolete.
The resource are test only in the core and will be removed via YUNIKORN-175

None belong in the SI and will be removed in YUNIKORN-174

**Comment by adamantal** [comment]
Thank you @wilfred-s. According to your latest I don't touch these constants now (just rebased it to head). Is there anything else that needs to be done here?

**Comment by yangwwei** [comment]
Looks like there is nothing else needed here. Closing this now.

**Pull request closed without merging**
