### PR TITLE
[YUNIKORN-368] Pass namespace's parentQueue annotation to application tag

### PR DESCRIPTION
**Pull request by adamantal**

### CODE REVIEW

**Comment by yangwwei** [comment]
Hi @adamantal sorry for the late review. The change is pretty straightforward, I only have one comment regarding the structure, basically, I think returning 2 values from `getTagsFromNamespaceAnnotations()` is not very flexible, in case we are going to parse more things from the namespace. I suggest changing this to

```
// update application tags in the AddApplicationRequest based on the namespace annotation
func (ctx *Context) updateApplicationTags(request *interfaces.AddApplicationRequest, namespace string) {
  // adding tags to request based on annotations
  // include
  //    - namespace.resourcequota
  //    - namespace.parentqueue
}

func (ctx *Context) AddApplication(request *interfaces.AddApplicationRequest) interfaces.ManagedApp { 
  ...
  updateApplicationTags(request, ns)
  ...
}
```

**Comment by adamantal** [comment]
I have validated this patch. Configurations:

Namespace config:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    yunikorn.apache.org/parentqueue: "root.special"
  name: random
```

The pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "application-sleep-0001"
    namespace: "random"
    queue: "root.default"
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
```

Queue configs:
```yaml
partitions:
  - name: default
    placementrules:
      - name: tag
        value: namespace
        create: true
        parent:
          name: tag
          value: "namespace.parentqueue"
          create: true
    queues:
      - name: root
        submitacl: '*'
        queues:
          - name: default
            submitacl: '*'
          - name: special
            parent: true
            submitacl: '*'
            queues:
              - name: leaf 
```

The application was correctly put into queue `root.special.random`.

Note that:
- the app CRD *has to be turned off* (it is somehow intercepts the basic placement of the application)
- the Travis CI check is currently failing due to [YUNIKORN-389](https://issues.apache.org/jira/browse/YUNIKORN-389)
- I also found a scheduler crash during testing, filed [YUNIKORN-390](https://issues.apache.org/jira/browse/YUNIKORN-390) for that

**Comment by yangwwei** [comment]
hi @adamantal This PR looks good to me, but I guess we need to merge YUNIKORN-389 to get a clean travis validation first. Let me look at that one and get back to this. Thank you for validating this.

**Comment by yangwwei** [comment]
hi @adamantal pls fix the remaining code coverage issue. rest looks good to me. Thanks

**Comment by adamantal** [comment]
Thanks for checking @yangwwei. Yes indeed, I forgot to add unit tests. Since the quota is also untested I added a test to cover the both. I'll check the Travis results and fix it if something else is missing.

**Review by yangwwei — APPROVED** [review]
All look good, thanks @adamantal 
Can you file a follow-up JIRA to update the user doc for this? We need to doc the steps how to do this in here: http://yunikorn.apache.org/docs/next/user_guide/resource_quota_management

**Comment by adamantal** [comment]
Thanks for merging this in @yangwwei . Filed [YUNIKORN-398](https://issues.apache.org/jira/browse/YUNIKORN-398) for the issue.

**Pull request merged**
