### PR TITLE
[YUNIKORN-496] Add port-forward loop and remove unnecessary test output

### PR DESCRIPTION
**Pull request by ronazhan**

### CODE REVIEW

**Comment by yangwwei** [comment]
The UT failure is not from this PR, created https://issues.apache.org/jira/browse/YUNIKORN-499 to check.

**Comment by ayubpathan** [comment]
@yangwwei  The build seems to be failing. Is this due to an existing issue?

**Comment by yangwwei** [comment]
> @yangwwei The build seems to be failing. Is this due to an existing issue?

Correct. There is a data race tracked in https://issues.apache.org/jira/browse/YUNIKORN-499. I am working on a fix for this. We can retrigger the build once that is fixed. In the meantime, can you help to review the changes in this PR?

**Comment by yangwwei** [comment]
hi @ronazhan , https://issues.apache.org/jira/browse/YUNIKORN-499 now has been fixed, could you please update the dependency by using

```
go get github.com/apache/incubator-yunikorn-core@master
``` 

and update this PR? The UT failure should be gone in the next run. Thanks

**Comment by ayubpathan** [comment]
LGTM.
@yangwwei  Could you please help merge this one?

**Pull request merged**
