### PR TITLE
[YUNIKORN-411] Refactor podConfigs and configMap

### PR DESCRIPTION
**Pull request by ronazhan**
Adding new podConfig and configMap structs to framework. Also updates the old tests to use these formats instead of previously hard-coded versions. 

- Substitute pod config
- Substitute config map

### CODE REVIEW

**Comment by ronazhan** [comment]
@ayubpathan Can you review?

**Comment by yangwwei** [comment]
hi @ayubpathan could u pls help to review the PR? Thanks

**Comment by ayubpathan** [comment]
LGTM. Thanks @ronazhan for working on this!

**Comment by ayubpathan** [comment]
@yangwwei  Could you please help merge this one?

**Comment by yangwwei** [comment]
Thanks for the PR @ronazhan , and thanks for the review @ayubpathan . 
+1, I will merge this shortly.

**Pull request merged**
