### PR TITLE
[YUNIKORN-1084] Update namespace handling in admission controller

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
Update the namespace handling in the admission controller to be more comprehensive. This will handle all cases where namespaces should be processed or bypassed, and labeled or not labeled.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1084

### How should this be tested?
Unit tests added.

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
`parseRegexes` really needs a test
* garbage input causes failure
* more than 1 reg exp in string (split check)
* escape character, i.e. what happens with a \, do we see expected result
Just some sanity checks so we know it works

**Comment by craigcondit** [comment]
> `parseRegexes` really needs a test
> 
> * garbage input causes failure
> * more than 1 reg exp in string (split check)
> * escape character, i.e. what happens with a , do we see expected result
>   Just some sanity checks so we know it works

Added more tests in latest commit. Have verified 100% coverage of all lines / branches in parseRegexes() and initAdmissionController().

**Comment by craigcondit** [comment]
@wilfred-s, @yangwwei can you review?

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
