### PR TITLE
[YUNIKORN-977] Revert YUNIKORN-885 - Set health check as liveness probe

### PR DESCRIPTION
**Pull request by craigcondit**
Revert "[YUNIKORN-885] Set healtch check as liveness probe (#317)"

This reverts commit a8b472fbc6f3c7b733844215e5e43b358c17f814.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-977

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
I will also backport this to branch-0.12 as it is a release blocker, once approved.

**Comment by craigcondit** [comment]
@yuchaoran2011 can you review?

**Comment by yangwwei** [comment]
Thank you @craigcondit , make sense. Approved the PR. Is this one causing [YUNIKORN-975](https://issues.apache.org/jira/browse/YUNIKORN-975) as well?

**Comment by craigcondit** [comment]
@yangwwei , YUNIKORN-975 is still under investigation. I am going to continue troubleshooting this today, after reverting these commits.

**Pull request closed without merging**
