### PR TITLE
[YUNIKORN-1108] Follow-up: Fix race conditions in dispatcher_test.go

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Follow-up on YUNIKORN-1108. Creating a new dispatcher for every test case.
Removed the unnenecessary nil check in initDispatcher().

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1108

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
In a number of tests we manipulate the dispatcher and use defer calls to fix up the exact changes made one at a time. This could be simplified to just replacing the whole dispatcher with a clean one via a defer call:
```
initDispatcher()
defer initDispatcher()
```
We do not need to track or reset things one by one as we know the dispatcher will be thrown away. Simplifies the code even further. Cleanup diff: +5, -15 lines if I count correctly.

**Comment by pbacsko** [comment]
> In a number of tests we manipulate the dispatcher and use defer calls to fix up the exact changes made one at a time. This could be simplified to just replacing the whole dispatcher with a clean one via a defer call:
> 
> ```
> initDispatcher()
> defer initDispatcher()
> ```
> 
> We do not need to track or reset things one by one as we know the dispatcher will be thrown away. Simplifies the code even further. Cleanup diff: +5, -15 lines if I count correctly.

I ended up with only -15 :) pls check.

**Comment by pbacsko** [comment]
Wow, we still have data races. Let me investigate this further...

**Comment by pbacsko** [comment]
`TestExceedAsyncDispatchLimit()` doesn't even run on its own. There are more problems in the test module.

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
